bz2:
	cc Bz2.c -o Bz2
	./Bz2
	rm Bz2

bz4:
	cc Bz4.c -o Bz4
	./Bz4
	rm Bz4

Bz4_sw:
	cc   -lncurses  Bz4_sw.c   -o Bz4_sw
	./Bz4_sw
	rm Bz4_sw

Bz2_sw:
	cc   -lncurses  Bz2_sw.c   -o Bz2_sw
	./Bz2_sw
	rm Bz2_sw

Bz1_sw:
	cc   -lncurses  Bz1_sw.c   -o Bz1_sw
	./Bz1_sw
	rm Bz1_sw